device_id: "你的设备key"
group_id: "xxx你的key"
nats_url: "nats://10.20.15.242:4222"
chunk_size: 8388608
token_ttl: 60
poll_interval_ms: 500
cache_dir: ""
download_dir: ""
mount_dir: ""
log_level: "error"
clipboard_file_format: "uri-list"
